heat_template_version: 2015-10-15
description: Launch an instance with Ubuntu Xenial image to run the server.

parameters:

  key_name:
    type: string
    description: Name of an existing key pair to use for the server
    default: cle
    constraints:
      - custom_constraint: nova.keypair

  flavor:
    type: string
    description: Flavor for the server to be created
    default: 2048-10-1-1
    constraints:
      - custom_constraint: nova.flavor

  image:
    type: string
    description: Image ID or image name to use for the server
    default: xenial-server-cloudimg-amd64-disk1
    constraints:
      - custom_constraint: glance.image

  network:
    type: string
    default: 9ec556ab-d458-470e-96bc-1bab0ef66fb9
    description: Network ID to use for the instance.

  subnet:
    type: string
    description: ID of private sub network into which servers get deployed
    default: 4ba321db-9247-454b-9274-faad8ec76461

  pool_id:
    type: string
    description: Pool to contact

  metadata:
    type: json

  user_data:
    type: string
    description: Server user_data

resources:

  server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      image: {get_param: image}
      key_name: {get_param: key_name}
      metadata: {get_param: metadata}
      user_data: {get_param: user_data}
      user_data_format: RAW
      networks: [{network: {get_param: private_net_id} }]

  pool_member:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: {get_param: pool_id}
      address: { get_attr: [ server, first_address ]}
      protocol_port: 8080
      subnet: { get_param: private_subnet_id }
